spring:
  application:
    name: excel-importer
  datasource:
    url: jdbc:postgresql://localhost:5432/import
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
